### ISSUE TITLE
integration into libstd

### ISSUE THREAD

**Issue by est31** [gimli-rs/addr2line#89]
Hi, has integration into libstd been attempted yet (https://github.com/rust-lang/rust/issues/46439)? Have there been any blockers that are not resolved yet? If no, I'd like to conduct such a project.

Blockers for addr2line itself (in no particular order):

- [x] port gimli to `#![no_std]` (https://github.com/gimli-rs/gimli/issues/138)
- [x] gimli release with `#![no_std]` support (https://github.com/gimli-rs/gimli/issues/303)
- [x] make gimli use stable_deref_trait 1.1.0 and use it without it depending on std (https://github.com/gimli-rs/gimli/pull/306 )
- [x] gimli release that includes the modified entry for `stable_deref_trait` ([0.16.1](https://github.com/gimli-rs/gimli/releases/tag/0.16.1))
- [x] `StableDeref` impls for `#![no_std]` types in `stable_deref_trait` (https://github.com/Storyyeller/stable_deref_trait/pull/2)
- [x] update addr2line to gimli 0.16.0 (https://github.com/gimli-rs/addr2line/pull/91)
- [x] update addr2line to object 0.9.0 (https://github.com/gimli-rs/addr2line/pull/93)
- [x] port cpp_demangle to `#![no_std]` (https://github.com/gimli-rs/cpp_demangle/pull/146 , https://github.com/gimli-rs/cpp_demangle/pull/148)
- [x] cpp_demangle release with `#![no_std]` support ([0.2.10](https://github.com/gimli-rs/cpp_demangle/releases/tag/0.2.10))
- [x] add `#![no_std]` to lazycell (https://github.com/indiv0/lazycell/pull/85)
- [x] lazycell release with `#![no_std]` (https://github.com/indiv0/lazycell/pull/86)
- [x] port addr2line from lazy-init to lazycell (https://github.com/gimli-rs/addr2line/pull/94)
- [x] port addr2line to `#![no_std]` (https://github.com/gimli-rs/addr2line/issues/90, #102)
- [x] addr2line release with `#![no_std]` support ([here](https://github.com/gimli-rs/addr2line/releases/tag/0.7.0))

**Comment by fitzgen** [comment]
This crate is for symbolicating addresses, which is only half the story. The other half is walkign the stack to get the addresses for symbolication. There is a WIP crate for that [here](https://github.com/gimli-rs/unwind-rs), but it needs lots of love to get into a place where it could go into rustc, I suspect.

That said, I would also love to see that happen. It is "just" a matter of doing the (substantial amount of) work :)

**Comment by main--** [comment]
My work on unwind-rs has pretty much stalled for now as I got tied up in other projects. It works fine on x86_64 but that's about it. For me to continue on this there would need to be some serious interest from the rustc side as well as another contributor, I don't have the time (nor the hardware) to do it all alone.

AFAIK addr2line is quite solid at this point and using that for symbolication instead of libbacktrace in rustc should work in principle (naturally, I would expect the bigger exposure to discover a few bugs).

**Comment by est31** [comment]
According to [this comment](https://github.com/rust-lang/rust/issues/46439#issuecomment-348699742), libbacktrace isn't used for walking the stack, so addr2line integration alone would allow us to remove libbacktrace.

**Comment by philipc** [comment]
Yep, my understanding is that libunwind is used for walking the stack, both for backtraces and unwinding after panics, and libbacktrace is used for symbolication. addr2line is suitable for symbolication, such as in [backtrace-rs](https://github.com/alexcrichton/backtrace-rs/blob/master/src/symbolize/gimli.rs).

I think one of the blockers was getting no_std support, based on [this comment](https://github.com/rust-lang/rust/pull/44251#issuecomment-355981816). That has been done in the object crate, but addr2line still needs updating (I have done some work on this but it's currently blocked on a new gimli release).

For addr2line to be usable on OSX, we also need to hook up something like https://github.com/gimli-rs/moria to find the DWARF, but that can probably be done externally to addr2line. There's also the possible need to get it from object files (#87). Both of these can come after getting linux support working though.

**Comment by est31** [comment]
> I think one of the blockers was getting no_std support

Thanks, I've filed a bug for a new gimli release as well as no_std support and added them to the newly created blocker list above.

> For addr2line to be usable on OSX

To my knowledge, right now we don't support backtraces on OSX anyway. So an initial version can ship without MacOS support just fine.

**Comment by luser** [comment]
> For addr2line to be usable on OSX, we also need to hook up something like https://github.com/gimli-rs/moria to find the DWARF, but that can probably be done externally to addr2line. 

This sounds right. FWIW, `moria` is trying to be a general-purpose crate, but for Rust standard library purposes you could probably get away with something simple like:
https://github.com/gimli-rs/moria/blob/b38bbf1f165f9dc874b9ea69a277c4857b61d7cd/src/lib.rs#L194

You'd just need to get the UUID from the `LC_UUID` load command in the Mach-O headers, but that's not hard.

**Comment by est31** [comment]
The release has since happened so all items on the list I have made last year are checked. However I'm not closing this issue, as instead of my PR https://github.com/rust-lang/rust/pull/51440 , acrichto's PR https://github.com/rust-lang/rust/pull/56092 got merged. My PR only required `#![no_std]` support, but now, special code in Cargo.toml is needed as well. This needs to be done on all of addr2line's recursive dependencies. See a detailed list [here](https://github.com/rust-lang/rust/issues/46439#issuecomment-492710756). If anyone wants to revive my PR, I'm happy to help.

**Comment by philipc** [comment]
I think this will be fixed by #166
